apiVersion: v1
kind: ReplicationController
metadata:
  name: server 
spec:
  replicas: 3
  selector:
    app: server 
  template:
    metadata:
      name: server
      labels:
        app: server 
    spec:
      containers:
      - name: server 
        image: fisache/go-helloworld-server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 50051 
---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  selector:
    app: server 
  ports:
  - port: 50051 
    protocol: TCP
    targetPort: 50051 
  type: NodePort

