apiVersion: v1
kind: ReplicationController
metadata:
  name: client 
spec:
  replicas: 1 
  selector:
    app: client 
  template:
    metadata:
      name: client
      labels:
        app: client 
    spec:
      containers:
      - name: client 
        image: fisache/go-helloworld-client:latest
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: client
spec:
  selector:
    app: client 
  ports:
  - port: 80 
    protocol: TCP
    targetPort: 80 
  type: NodePort

